# Generated by Django 5.2.6 on 2025-09-13 18:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_veg', models.BooleanField(default=True)),
                ('available', models.BooleanField(default=True)),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], max_length=10)),
                ('served_date', models.DateField(default=django.utils.timezone.localdate)),
                ('image', models.ImageField(blank=True, null=True, upload_to='dishes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('canteen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-served_date', 'meal_type', 'name'],
            },
        ),
    ]
