# Generated by Django 5.1.1 on 2025-09-26 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='pickup_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
